
import React from 'react'


export const metadata = {
    title: 'About Next js',
    description: 'Generated by create next app',
  }
const Aboutpage = () => {
  return (
    <div>
        <h1>Welcome to About</h1>
        <p>
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typese
        </p>
    </div>
  );
};

export default Aboutpage;